# Default values for refarch-ocp4-gitops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cloudProvider: vSphere
infrastructureId: waiops-pqtxb


vsphere:
  networkName: vdpg-192.168.100
  datacenter: dc01
  datastore: openshift
  folder: /dc01/vm/waiops-pqtxb
  resourcePool: /dc01/host/cluster01/Resources
  server: vcsa67.rtp.raleigh.ibm.com
  infraNodes:
    nodeCount: 3
    diskGiB: 120
    memoryMiB: 16384
    numCPUs: 4
    numCoresPerSocket: 1
  storageNodes:
    nodeCount: 3
    diskGiB: 120
    memoryMiB: 65536
    numCPUs: 16
    numCoresPerSocket: 1
