
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: refarch-storageconfig
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://ncolon.github.io/refarch-ocp4-gitops'
    targetRevision: 0.6.9
    chart: refarch-storageconfig
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      selfHeal: true

