apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storageconfig
  namespace: tools
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://ncolon.github.io/refarch-ocp4-gitops'
    targetRevision: 0.1.0
    chart: refarch-storageconfig
  project: default
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
      selfHeal: true

