{{ $test:= required "error message" .Values.infrastructureId }}
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: cp4x
  annotations:
  
spec:
  machineConfigSelector:
    matchExpressions:
      - {key: machineconfiguration.openshift.io/role, operator: In, values: [worker,cp4x]}
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/cp4x: ""
---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
  name: {{ .Values.infrastructureId }}-cp4x
  namespace: openshift-machine-api
spec:
  replicas: 4
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.infrastructureId }}-cp4x
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: {{ .Values.infrastructureId }}-cp4x
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/cp4x: ""
      providerSpec:
        value:
          {{- if eq .Values.cloudProvider "vSphere" }}
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: {{ .Values.vsphere.cloudpakNodes.diskGiB }}
          kind: VSphereMachineProviderSpec
          memoryMiB: {{ .Values.vsphere.cloudpakNodes.memoryMiB }}
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: {{ .Values.vsphere.networkName }}
          numCPUs: {{ .Values.vsphere.cloudpakNodes.numCPUs }}
          numCoresPerSocket: {{ .Values.vsphere.cloudpakNodes.numCoresPerSocket }}
          snapshot: ""
          template: {{ .Values.infrastructureId }}-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: {{ .Values.vsphere.datacenter }}
            datastore: {{ .Values.vsphere.datastore }}
            folder: /{{ .Values.vsphere.datacenter }}/vm/{{ .Values.infrastructureId }}
            resourcePool: /{{ .Values.vsphere.datacenter }}/host/{{ .Values.vsphere.cluster }}/Resources
            server: {{ .Values.vsphere.server }}
          {{- end}}
