{{- if .Values.ocs.installOCS }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ocs-operator
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "3"
spec:
  channel: {{ .Values.ocs.channel }}
  installPlanApproval: Automatic
  name: ocs-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ocs-operator.v{{ .Values.ocs.version }}
{{- end }}