# Default values for refarch-ocp4-gitops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

argonamespace: argocd

registry:
  storageClassName: ocs-storagecluster-cephfs
  replicas: 2

ingress:
  replicas: 2
