# Default values for refarch-ocp4-gitops.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


storage:
  rwxStorageClass: ocs-storagecluster-cephfs
  rwoStorageClass: ocs-storagecluster-ceph-rdb
