apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: {{ .Values.infrastructureId }}-infra
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
spec:
  replicas: {{ .Values.vsphere.infraNodes.nodeCount }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.infrastructureId }}-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.infrastructureId }}
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: {{ .Values.infrastructureId }}-infra
    spec:
      taints:
      - effect: NoSchedule
        key: infra
        value: reserved
      - effect: NoExecute
        key: infra
        value: reserved
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          {{- if eq .Values.cloudProvider "vSphere" }}
          apiVersion: vsphereprovider.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: {{ .Values.vsphere.infraNodes.diskGiB }}
          kind: VSphereMachineProviderSpec
          memoryMiB: {{ .Values.vsphere.infraNodes.memoryMiB }}
          metadata:
            creationTimestamp: null
          network:
            devices:
            - networkName: {{ .Values.vsphere.networkName }}
          numCPUs: {{ .Values.vsphere.infraNodes.numCPUs }}
          numCoresPerSocket: {{ .Values.vsphere.infraNodes.numCoresPerSocket }}
          snapshot: ""
          template: {{ .Values.infrastructureId }}-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: {{ .Values.vsphere.datacenter }}
            datastore: {{ .Values.vsphere.datastore }}
            folder: {{ .Values.vsphere.folder }}
            resourcePool: {{ .Values.vsphere.resourcePool }}
            server: {{ .Values.vsphere.server }}
          {{- end}}
